CREATE TABLE IF NOT EXISTS ListNomenclatures (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	libelle VARCHAR(30) NOT NULL,
	racine INT UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(racine) REFERENCES Pieces(id)
)
;